"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Provider } from "jotai";
import { SessionProvider } from "next-auth/react";
import Navbar from "../components/navbar/Navbar";
const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
    children,
    session,
}: Readonly<{
    children: React.ReactNode;
    session: any;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <SessionProvider session={session}>
                    <Provider>
                        <Navbar />
                        {children}
                    </Provider>
                </SessionProvider>
            </body>
        </html>
    );
}
